title: Le soussteme dominant
description: Jaaj 4 ever

remote_theme: daviddarnes/garth

plugins:
  - jekyll-remote-theme

collections:
  lexique:
    output: true
    permalink: /lexique/:name/

defaults:
  - scope:
      path: ""
      type: "lexique"
    values:
      layout: page

nav:
  - title: Accueil
    url: /
  - title: Blog
    url: /blog/
  - title: Lexique
    url: /lexique/
